### ISSUE TITLE
Implement repetition "weekly"

### ISSUE THREAD

**Issue by egithinji** [tijlleenders/ZinZen-scheduler#107]
To allow someone to specify something to be done once a week without specifying which day of the week. e.g. "study french duration 2hrs once a week". Also should be able to handle time bounds e.g. "study french duration 2hrs once a week, but between 6pm and 10pm"

**Comment by tijlleenders** [comment]
We should discuss the way of writing on the frontend and the way of communicating this to the backend with @Tushar-4781 and @JacobJax . Right now we have a repetition field, but for speed and simplicity we might want to start with a more strict specification like "x-y per duration" instead of "once/twice/three times per week". This makes it easier to recognize in the input goal parser.

Maybe we can add a field 'testTitle' so that this can be encoded in the testcases - avoiding the need of extra separate and hard to maintain documentation.

**Comment by egithinji** [comment]
What I'm describing in this issue is a simple case like this:

"goals": [
    {
      "id": 1,
      "title": "study french",
      "duration": 2,
      "repeat": "weekly",
      "after_time": 6,
      "before_time": 10
    }
  ]

**Comment by tijlleenders** [comment]
I propose we first make a test to unit test the weekly.
After that combine it with other constraints like after_time etc.

**Comment by egithinji** [comment]
Sure, that's a good idea.
