### ISSUE TITLE
Can we change "start" and "deadline" fields

### ISSUE THREAD

**Issue by egithinji** [tijlleenders/ZinZen-scheduler#151]
I suggest we rename `start` and `deadline` fields in the input to `after_date` and `before_date`. This will make it easier to reason about because we're using `start` and `deadline` as date bounds, the same way we use `after_time` and `before_time` as time bounds.

Currently we define our goals like this:

{
          "id": 1,
          "title": "shopping",
          "duration": 1,
          "start": "2022-01-01T00:00:00",
          "deadline": "2022-01-02T00:00:00",
          "after_time": 10,
          "before_time": 13
}

Why can't we change it to this:

{
          "id": 1,
          "title": "shopping",
          "duration": 1,
          "after_date": "2022-01-01T00:00:00",
          "before_date": "2022-01-02T00:00:00",
          "after_time": 10,
          "before_time": 13
}

**Comment by tijlleenders** [comment]
In the scheduler that makes sense - but then I'd suggest 'after_datetime'.

Keep in mind the UI will still give it to the scheduler as after and deadline - so you'll have to do the translation on deserialization. I think there's an optiom for renaming on the fly.

On the UI side after and deadline makes more sense because that's how it is typed and shown to the user.

**Comment by tijlleenders** [comment]
Started https://github.com/tijlleenders/ZinZen/issues/706 since start and deadline i  combination with a time doesn't work in the current parser.

**Comment by tijlleenders** [comment]
@egithinji The frontend uses start and due because:
- afterDateTime and beforeDateTime is too long a name for a tag
- using after and before is confusing with the date-independent time constraint after/before

I'm ok renaming it to after_datetime and before_datetime - but isn't that confusing on the scheduler side too with the pre-existing after_time and before_time?

**Comment by tijlleenders** [comment]
If you do rename it, Tushar will have to do a conversion to your new input schema since we decided the UI is responsible for converting any discrepancies in naming between the UI and the scheduler (see https://github.com/tijlleenders/ZinZen/issues/684#issuecomment-1295926352)

**Comment by tijlleenders** [comment]
@egithinji Let's close this issue.

>"I'm ok renaming it to after_datetime and before_datetime - but isn't that confusing on the scheduler side too with the pre-existing after_time and before_time?"

Does that work for you?

**Comment by egithinji** [comment]
Yeah that's fine since we've made progress with the current naming anyway.
