### ISSUE TITLE
Confusion: Output shows tasks not slots

### ISSUE THREAD

**Issue by moaz-mokhtar** [tijlleenders/ZinZen-scheduler#294]
As discussed before that scheduler behavior regarding taking goals and schedule tasks as below:
- `Goal`s separated to `Task`s
- `Task`s separated into `Slot`s

That means if we have below `goal`s:
```
Goal: 1, "work", daily, ...
Goal: 2, "study", daily, ...
```

So `output` should be summarized as below:
```
For Goal: 1, "work", daily, ...
Tasks are: [
    - { goal_id: 1, task_id: 1, slot_id: 1, "work", 2023-04-01 8am-5pm, ... }
    - { goal_id: 1, task_id: 1, slot_id: 2, "work", 2023-04-02 8am-5pm, ... }
    - { goal_id: 1, task_id: 1, slot_id: 3, "work", 2023-04-03 8am-5pm, ... }
    ...
 ]

===

For Goal: 2, "study", daily, ...
Tasks are: [
    - { goal_id: 2, task_id: 1, slot_id: 1, "study", 2023-04-01 7pm-8pm, ... }
    - { goal_id: 2, task_id: 1, slot_id: 2, "study", 2023-04-02 7pm-8pm, ... }
    - { goal_id: 2, task_id: 1, slot_id: 3, "study", 2023-04-03 7pm-8pm, ... }
    ...
 ]
```

So `task`s will be separated into `slot`s which means we have to identify them by `slotid`.

I got this confusion while I'm investigating https://github.com/tijlleenders/ZinZen-scheduler/issues/289.
To make it clear, imagine you have below goal
```
Goal: 1, "sleep", daily, 9pm-8am, ...
```

Current implementation before issue #289, schedule will `output` below:
```
Goal: 1, "sleep", daily, 9pm-8am, ...
Tasks are: [
    - { goal_id: 1, task_id: 1, "sleep", 2023-04-01 09:00pm-11:59pm, ... }
    - { goal_id: 1, task_id: 2, "sleep", 2023-04-02 12:00am-08:00am, ... }
    - { goal_id: 1, task_id: 3, "sleep", 2023-04-02 09:00pm-11:59pm, ... }
    - { goal_id: 1, task_id: 4, "sleep", 2023-04-03 12:00am-08:00am, ... }
    ...
 ]
```
So that means we separating `goal`s into `task`s and actually no `slot`s except it is just a date for a `task`.

So as my understanding, we should fix this confusion and `output` should be as below:
```
Goal: 1, "sleep", daily, 9pm-8am, ...
Tasks are: [
    - { goal_id: 1, task_id: 1, slot_id: 1, "sleep", 2023-04-01 09:00pm-11:59pm, ... }
    - { goal_id: 1, task_id: 1, slot_id: 2, "sleep", 2023-04-02 12:00am-08:00am, ... }
    - { goal_id: 1, task_id: 1, slot_id: 3, "sleep", 2023-04-02 09:00pm-11:59pm, ... }
    - { goal_id: 1, task_id: 1, slot_id: 3, "sleep", 2023-04-03 12:00am-08:00am, ... }
    ...
 ]
```

After basic debugging for `i287_mix_budgets_single_goal` and `split_4`, I found that slots are empty in the list of `task`s to be `output`.
![image](https://user-images.githubusercontent.com/5870208/231300400-a81eca5f-dfee-46e8-a56e-60d71e96901d.png)

**Comment by tijlleenders** [comment]
Hi @moaz-mokhtar 
Thanks for asking clarification.

If you look at the Task struct you'll see that time slots are a property of Task. There can be multiple slots for one Task and they don't require an id. It is just the Tasks private view of the interesting and allowed spots on the calendar.

If I have a calendar of one day and a goal of 1h with a filter before 8 and after 22, the resulting Task (before task_placer looks at it) will have two slots - one from 0-8 and from 22-0.
The task_placer - when it gets around to scheduling this task - will then pick the first suitable slot that is not 'wanted' by any other Task. If all slots are 'wanted' it will pick the one which is least 'wanted' by other Tasks.

The order in which task_placer handles tasks is determined by the Task flexibility: first all Tasks with flex 1, then from highest to lowest.  After each placement the flexibility gets recalculated.

**Comment by tijlleenders** [comment]
@moaz-mokhtar Can this be closed now?

**Comment by moaz-mokhtar** [comment]
I think I couldn't show my confusion clearly which is simply: `why many tasks appeared in the output for one single task with many slots!!!`.

I'm proposing something like  `OutputSlot` which will contain list of `slot`s for each single `task`. By this way to can define each `OutputSlot` with an Id:
```
- Goal is "sleep", daily, 9pm-8am, 2023-03-01 till 2023-03-31.
- Goal 1 divided into one task. Task id: 1 for Sleep.
- Task 1 contains 29 slots.
- Output is: [
    - output_slot { id: 1, Goal: 1, Task: 1, name: sleep, start_time: <DATE> 21:00 , end_time: <DATE> 08:00 , etc }
    - output_slot { id: 1, Goal: 1, Task: 1, name: sleep, start_time: <DATE> 21:00 , end_time: <DATE> 08:00 , etc }
    ...
 ]
```

**Comment by tijlleenders** [comment]
@moaz-mokhtar This is so that the frontend doesn't have to do any work.
The MyTime page needs to present a calendar with the different Tasks/Slots per day.
It doesn't care about anything but Task and GoalId.

So a Task for the frontend is basically a Slot+GoalId from the backend.
@Tushar-4781 Maybe we can rename this to OutputSlot instead of Task like Moaz proposes?

**Comment by tijlleenders** [comment]
Discussed this with @moaz-mokhtar  
The consensus is that everything starts with `Goals` and ends with a schedule of `Tasks`.  
`Tasks` is more intuitive than `Actions` since everyone is used to this from todo apps - **so let's settle on `Goals` and `Tasks`**.  

**The challenge remains what to name the thing in between - that is _now_ not known in the frontend** - but is known in the scheduler. It could later be necessary to also have to be known/named in the frontend to indicate completion stats on habits. The unit of a habit would not be `Task` but the daily/weekly container of `Tasks`.  
Examples: 
1. A `goal` "Exercise 2h daily" possibly gets split into 1h in the morning and 1h in the afternoon  
On the 'completion rate' of the Habit you'd want to see how many times you achieve the daily goal, not if you only achieve half of it.
2. A goal "Read a book monthly" will get divided into many Tasks.  
On the 'completion rate' of the Habit you'd want to see how many times you achieve the monthly goal, not a completion indicator for each individual Task - which can also be postponed and doesn't provide useful information when comparing month to month...

**Comment by tijlleenders** [comment]
`Goals` get divided into `Sprints` of `Tasks`?

**Comment by tijlleenders** [comment]
How about this: `Goals` turn into `Steps`:
- either by repeating the Goal, if it's something like 'Run 1h' repeated 3x/week
- by splitting the goal into smaller steps, like a big 50h project, worked on 3h/week

Every `Step` is realized/scheduled by on or more `Tasks` on the calendar.  
@moaz-mokhtar This would mean renaming current `Tasks` in scheduler code to `Steps`.
When the `Step` timeline is final (Step is scheduled) the output formatter can turn this into a schedule of `Tasks`.

**Comment by tijlleenders** [comment]
@moaz-mokhtar 
The `steps` concept is only relevant for the front-end when making habit-tracker reports. Dropping the `step` concept in the frontend and instead just registering the most granular level of detail will give us more flexibility do do whatever we want in terms of reporting. So we just register what has been completed/rescheduled when - without linking it to a particular `step`.  

For the scheduler it is still relevant in my opinion.  

**I propose to rename the current _scheduler_ `Task` to `Step`.**  
`Task` in the backend would then only refer to the individual slots in the output of the scheduler.   
**That would resolve this issue, agree?**

**Comment by moaz-mokhtar** [comment]
Should we close this which resolved by PR https://github.com/tijlleenders/ZinZen-scheduler/pull/332
