### ISSUE TITLE
Feature request: Logging

### ISSUE THREAD

**Issue by moaz-mokhtar** [tijlleenders/ZinZen-scheduler#298]
**Is your feature request related to a problem? Please describe.**
Yes, related to debug issues and bugs. Preferred to save logging, so we can trace issues for future requests.

**Describe the solution you'd like**
A way of logging which can help debugging and tracing issues specially when asking many users to test and give a feedback.
I don't have a specific design at the moment.

**Comment by tijlleenders** [comment]
Logging is fine - just use a standard library for it.
Also, make sure it is not included in the wasm - so it doesn't make the binary larger than necessary.

**Comment by tijlleenders** [comment]
@moaz-mokhtar 
Just to be more explicit:
I think for now we only require Rust logging - not Wasm logging - because we do all of the dev work on the Rust side, right?

For Wasm side - we can catch any errors in the schedule function and put it in the output - so that it can be logged by the console. Actually, even better: use [console_error_panic_hook](https://crates.io/crates/console_error_panic_hook). We're already including it in the Cargo.toml - but don't think we're activating it anywhere...

This means we don't have to use any Wasm logging library on top of a Rust logging library. 

The only requirements I see for the Rust logging library are:
- simple to add in code (max one line of code per call)
- configurable log levels
- should be excludable when compiling for Wasm
Some options to evaluate: https://docs.rs/log/latest/log/#available-logging-implementations

PS: we're currently including simple_logger in Cargo.toml but don't think we're using it?

**Comment by moaz-mokhtar** [comment]
Ok I will figure this and will feedback you

**Comment by tijlleenders** [comment]
This was implemented by @kobe-reygel in https://github.com/tijlleenders/ZinZen-scheduler/commit/b33329497a51f4ead9dcfd6e4d2d79cf5b48cd0d
