### ISSUE TITLE
Split Steps while placing based on rule

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen-scheduler#318]
@moaz-mokhtar 

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.  
I would get frustrated if there are too many UI timing options. 

**Describe the solution you'd like**
When I type "sleep 8h daily" I *obviously?* don't want to do that in 2 h chunks spread over the day (or an uberman schedule for that)... but for anything else the default should be to not split Steps in placer. Unless it's something like "Work 40h weekly".  
So there needs to be some kind of rule that allows the UI/scheduler to automatically know if splitting while placing is allowed - or to automatically set a UI option checkbox so I don't have to manually - but do get informed.

**Describe alternatives you've considered**
All or nothing approach that doesn't work.  
Interactive approach that requires to confirm split when it is not possible to place otherwise.  
Split only if not possible to place otherwise (but thay doesn't solve the sleep case where you want to forve non-split).

**Additional context**
We are in the process of making any slot in the timeline of a step non-contiguous. This is a different kind of non-split as it is not about the actualnplacements but about the potential slots.

**Comment by moaz-mokhtar** [comment]
Initially, we have a parameter `min_duration` which force minimum duration for each Step/Task block.
But current implementation splitting blocks without consider `min_duration` as minimum duration for each block.

So that means default behavior is "split Step/Task block duration restricted to `min_duration` and `max_duration`". I don't think if this issue have been fixed in the current implementation will affect the case `Work 40h weekly`.

But we can add a boolean parameter like `is_block_splitable` in the `input.json` so if this parameter is true, each Task/Step block will splitable whether it is `sleep 8hrs/daily` or `Work 40hrs weekly` case?

**Comment by tijlleenders** [comment]
I don't like adding flags. This issue is about coming up with an alternative, a way to _deduce_ the splittable boolean from the existing regular inputs: a business rule.   

I think for now we can use the (not yet implemented) max_times_per_day budget for this? Setting that to 1 in combination with min_duration_per_day set to min_duration would have the same effect.  
Since task_placer Step iterations start at the after time this would also work for "Sleep 8h 22-6"?

**Comment by moaz-mokhtar** [comment]
So as agreed, it make sense to apply rule:
```
if 0 < task.min_duration < 8 hours
  - make it one block
else [ min_duration > 8 hours ]:
  - split task into many tasks so no task exceed 8 hours
```

**Comment by moaz-mokhtar** [comment]
Agreed to change rule as below:
- Business rule applied now only on `Goal::generate_tasks` 
- if goal is leaf (doesn't have children), tasks to be splitted based on 8 hours rule

**Comment by moaz-mokhtar** [comment]
I think this issue not resolved completely and we may return back
