### ISSUE TITLE
test: create test case similar to `i287_mix_budgets_many_goals` but have impossible

### ISSUE THREAD

**Issue by moaz-mokhtar** [tijlleenders/ZinZen-scheduler#360]
Kindly create test case similar to `i287_mix_budgets_many_goals` but have impossible fields. It is not mandatory to be for long period, but it should have weekly and daily budgets then it contains impossible because the week is 'cut off' in the middle' by the requested calendar".
The test case will fail - since the expectation is that the requested calendar end shouldn't shorten the Step timeline.

**Comment by moaz-mokhtar** [comment]
After fixing PR https://github.com/tijlleenders/ZinZen-scheduler/pull/358 for case `i287_mix_budgets_many_goals`, should we close this issue?

**Comment by tijlleenders** [comment]
A Vec is a good fit since the Steps never have to change their order and we never remove any. We just need to walk the Vec, calculate flex to a tracking variable 'max_flex'.

We stop if we find 1.  
If not then override max if necessary.  
This replaces the sort/Ord. 
Fiktering Vec on status will be necessary.
