### ISSUE TITLE
ref: change data structure for `Vec<Step>` in struct `StepsToPlace`

### ISSUE THREAD

**Issue by moaz-mokhtar** [tijlleenders/ZinZen-scheduler#362]
**Describe the bug**
After resolving PR https://github.com/tijlleenders/ZinZen-scheduler/pull/358 for test case `i287_mix_budgets_many_goals`, found below issue:
- When many `Step`s for different `Goal`s  have the same flexibility, there is no specific criteria to sort them to start, that causing inconsistent scheduling which leads some `Step`s start first and some other `Step`s start first in different terminal/device.
- That is clearly appeared when testing case `i287_mix_budgets_many_goals` in my system and in Tijl's system.

So we need to force sorting on a specific criteria the list of `Step`s which is currently known as `Vec<Step>` in struct `StepsToPlace`

**Comment by tijlleenders** [comment]
Since we don't have a reliable way to reproduce this issue - it is hard to fix/debug.  
It doesn't occur often so not that important to fix.  

I'm also not sure the Vec datastructure is the reason for this happening. A Vec is ordered and is steps are generated based on an ordered BTreeMap of Goals .... so why would this be different between executions?  
Let's determine that first and have a way to reproduce the problem, before switching datastructures.

**Comment by tijlleenders** [comment]
No longer relevant with new scheduler approach from #411
