### ISSUE TITLE
mixed daily and weekly budgets only take daily budgets into account

### ISSUE THREAD

**Issue by kobe-reygel** [tijlleenders/ZinZen-scheduler#406]
**Describe the bug**
If we have both weekly and daily constraints, the daily minimum constraint is taken to be the most limiting factor. Even if the weekly minimum is more than 7 times the daily minimum.

**To Reproduce**

Take the test json tests/jsons/stable/i287-mix-budgets-many-goals/input.json
It has a daily constraint to " work" a minimum of 5 hours a day, and minimum 35 hours a week.

This test case schedules correctly at 5 hours a day, achieving the minimum for both constraints

Now change the test case to have a higher weekly minimum (e.g. 38).

EXPECTED: the scheduler schedules 3 extra hours vs. the previous run
ACTUAL: the output stays the same at 5 hours a day, thus not satisfying the minimum of 38 hours a week

**Additional context**
Noticed while correcting PR https://github.com/tijlleenders/ZinZen-scheduler/pull/395 for Issue 388. Ignored the problem there, because it is not a 'new bug' in the context of that PR

**Comment by kobe-reygel** [comment]
n.b. in https://github.com/tijlleenders/ZinZen-scheduler/pull/410 a testcase was added that should be fixed by fixing this bug.

**Comment by tijlleenders** [comment]
@kobe-reygel  
A key decision in how to implement this is whether we want a Budget object to know about all the Steps it is for (currently implemented) - or the Steps to know about the Budgets it belongs to.  

Changing the way this is implemented might make it easier to reason about?  

Instead of doing a lookup in the Budget struct mapping based on the (correctly?) derived Step id from the Goal id to see if the Placer is allowed to place a Step...  
the Placer would just check with the Budget  the Step claims it belongs to.

**Comment by tijlleenders** [comment]
@kobe-reygel I guess this can be closed unplanned with the new-scheduler approach?

**Comment by tijlleenders** [comment]
Closing this as no reply from @kobe-reygel - please reopen if necessary.
