### ISSUE TITLE
Whitespace in json makes test fail

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen-scheduler#417]
**Is your feature request related to a problem? Please describe.**
As part of https://github.com/tijlleenders/ZinZen-scheduler/pull/415 we validated some experimental tests.  
`sleep-1` and `weekly-2` fail, just because there is some whitespace in the json.

**Describe the solution you'd like**
Figure out why only these tests get extra whitespace and fix it.  
They are currently placed in /validated so they are not run on `cargo t`.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by kobe-reygel** [comment]
@tijlleenders these tests do not fail on extra whitespace - whitespace differences are already ignored (example in case: weekly-1 has the same formatting as weekly-2. It also has different whitespaces in expected.json and observed.json. It still passes)

These two tests fail because they panic. See attached screenshot for example.

I'm cancelling this issue and making a new one
<img width="656" alt="Screenshot 2023-11-14 at 21 51 37" src="https://github.com/tijlleenders/ZinZen-scheduler/assets/26096059/dcae1d69-994d-4688-8614-c66fa43d3bb9">
